version: "3.8"
services:
  postgres:
    container_name: template_postgres
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
    ports:
      - "5432:5432"
  graphql-engine:
    container_name: template__graphql_engine
    image: hasura/graphql-engine:v2.21.0
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: "${HASURA_GRAPHQL_DATABASE_URL}"
      PG_DATABASE_URL: "${HASURA_GRAPHQL_DATABASE_URL}"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
      HASURA_GRAPHQL_ACTIONS_BASE_URL: "${HASURA_GRAPHQL_ACTIONS_BASE_URL}"
      HASURA_GRAPHQL_DEFAULT_NAMING_CONVENTION: "graphql-default"
      HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: "naming_convention"
